#ifndef __DEBUGGING__
#define __DEBUGGING__

#include <string>
#include "automata.hpp"
#include "graph.hpp"

using namespace std;

/** Saves the automata as a graphviz dot file with an autogenerated name */
void guardar(Automata a);

/** Saves the automata a as a graphviz dot file with an custom name
 * appended with an autogenerated one */
void guardar(Automata a, const string & name);

/** Saves the LDGraph as a graphviz dot file with an autogenerated name */
void guardar(LDGraph a);

#endif // __DEBUGGING__
